import DS from 'ember-data';

export default DS.Model.extend({
  wrapperType: DS.attr('string'),
  kind: DS.attr('string'),
  artistId: DS.attr('string'),
  collectionId: DS.attr('string'),
  trackId: DS.attr('string'),
  artistName: DS.attr('string'),
  collectionName: DS.attr('string'),
  trackName: DS.attr('string'),
  collectionCensoredName: DS.attr('string'),
  trackCensoredName: DS.attr('string'),
  artistViewUrl: DS.attr('string'),
  collectionViewUrl: DS.attr('string'),
  trackViewUrl: DS.attr('string'),
  previewUrl: DS.attr('string'),
  artworkUrl30: DS.attr('string'),
  artworkUrl60: DS.attr('string'),
  artworkUrl100: DS.attr('string'),
  collectionPrice: DS.attr('string'),
  trackPrice: DS.attr('string'),
  releaseDate: DS.attr('string'),
  collectionExplicitness: DS.attr('string'),
  trackExplicitness: DS.attr('string'),
  discCount: DS.attr('string'),
  discNumber: DS.attr('string'),
  tarckCount: DS.attr('string'),
  trackTimeMillis: DS.attr('string'),
  country: DS.attr('string'),
  currency: DS.attr('string'),
  primaryGenreName: DS.attr('string'),
  isStreamable: DS.attr('string')

});

// {
// "wrapperType":"track", 
// "kind":"song", 
// "artistId":148662, 
// "collectionId":528436018, 
// "trackId":528437613, 
// "artistName":"LINKIN PARK", 
// "collectionName":"Hybrid Theory", 
// "trackName":"In the End", 
// "collectionCensoredName":"Hybrid Theory", 
// "trackCensoredName":"In the End", 
// "artistViewUrl":"https://itunes.apple.com/us/artist/linkin-park/id148662?uo=4", 
// "collectionViewUrl":"https://itunes.apple.com/us/album/in-the-end/id528436018?i=528437613&uo=4", 
// "trackViewUrl":"https://itunes.apple.com/us/album/in-the-end/id528436018?i=528437613&uo=4", 
// "previewUrl":"http://a665.phobos.apple.com/us/r1000/111/Music/a9/3f/fb/mzm.yidmhikq.aac.p.m4a", 
// "artworkUrl30":"http://is4.mzstatic.com/image/thumb/Music/v4/a3/da/73/a3da7362-c9f7-a6a4-bd00-632776ac74c1/source/30x30bb.jpg", 
// "artworkUrl60":"http://is4.mzstatic.com/image/thumb/Music/v4/a3/da/73/a3da7362-c9f7-a6a4-bd00-632776ac74c1/source/60x60bb.jpg", 
// "artworkUrl100":"http://is4.mzstatic.com/image/thumb/Music/v4/a3/da/73/a3da7362-c9f7-a6a4-bd00-632776ac74c1/source/100x100bb.jpg", 
// "collectionPrice":10.99, 
// "trackPrice":1.29, 
// "releaseDate":"2000-10-24T07:00:00Z", 
// "collectionExplicitness":"notExplicit", 
// "trackExplicitness":"notExplicit", 
// "discCount":1, 
// "discNumber":1, 
// "trackCount":12, 
// "trackNumber":8, 
// "trackTimeMillis":216294, 
// "country":"USA", 
// "currency":"USD", 
// "primaryGenreName":"Alternative", 
// "isStreamable":true}, 




